using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlaceableBuilding : MonoBehaviour
{
    [HideInInspector]
    public List<Collider> colliders = new List<Collider>();

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    void OnTriggerEnter(Collider c){
        if(c.tag == "Building"){
            colliders.Add(c);
        }
    }

    void OnTriggerExit(Collider c){
        if(c.tag == "Building"){
            colliders.Remove(c);
        }
    }
}
